// <auto-generated />
using System;
using ExamenU2Mario.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenU2Mario.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ExamenU2Mario.Entities.DetallePlanillaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Bonificaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("bonificaciones");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("comentarios");

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("deducciones");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("empleado_id");

                    b.Property<decimal>("HorasExtra")
                        .HasColumnType("TEXT")
                        .HasColumnName("horas_extra");

                    b.Property<decimal>("MontoHorasExtra")
                        .HasColumnType("TEXT")
                        .HasColumnName("monto_horas_extra");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planilla_id");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_base");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_neto");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("DetallesPlanilla");
                });

            modelBuilder.Entity("ExamenU2Mario.Entities.EmpleadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(13)
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellido");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("departamento");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("documento");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_contratacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("PuestoTrabajo")
                        .HasColumnType("TEXT")
                        .HasColumnName("puesto_trabajo");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("Salario_Base");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ExamenU2Mario.Entities.PlanillaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(13)
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo");

                    b.HasKey("Id");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("ExamenU2Mario.Entities.DetallePlanillaEntity", b =>
                {
                    b.HasOne("ExamenU2Mario.Entities.EmpleadoEntity", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenU2Mario.Entities.PlanillaEntity", "Planilla")
                        .WithMany()
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });
#pragma warning restore 612, 618
        }
    }
}
